name: Sync CSS Files

on:
  push:
    branches:
      - main

jobs:
  sync-css:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Debug - List directories
      run: |
        echo "Current directory contents:"
        ls -R

    - name: Copy CSS file
      run: |
        mkdir -p test-page
        cp output/css/tokensbrucke-htmlpagetest-variables.css test-page/ || echo "Copy failed"
        echo "Contents of test-page directory:"
        ls -l test-page

    - name: Debug - Show file contents
      run: |
        echo "Contents of source file:"
        cat output/css/tokensbrucke-htmlpagetest-variables.css
        echo "Contents of destination file:"
        cat test-page/tokensbrucke-htmlpagetest-variables.css

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -f test-page/tokensbrucke-htmlpagetest-variables.css
        git status
        git diff --staged
        git commit -m "Sync tokensbrucke-htmlpagetest-variables.css to test-page directory" || echo "No changes to commit"
        git push || echo "No changes to push"
